apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-replica
  labels:
    app: my-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: myapp
        image: vshamray1979/python_flask_return_hostname:v4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
